#!/bin/bash
echo $(date)" Starting Script" 
while true  
        do
        (cat /etc/clustermonitor/name; cat /proc/stat | grep cpu) | openssl rsautl -encrypt -inkey /etc/clustermonitor/server_public_key.pem -pubin | nc cluster.capella.pro 7001
        sleep 1
done  
