#! /bin/sh
rm -rf /usr/sbin/cclient
rm -rf /etc/init.d/clustermonitor

chmod u+x clustermonitor

cp cclient /usr/sbin/
cp clustermonitor /etc/init.d/

if [ ! -d /etc/clustermonitor ]; then
	mkdir /etc/clustermonitor
fi

if [ ! -d /etc/clustermonitor/tmp ]; then
	mkdir /etc/clustermonitor/tmp
	chmod -R 777 /etc/clustermonitor/tmp
fi

cp server.pem /etc/clustermonitor/
cd /etc/clustermonitor/

if [ ! -f private_key.pem ]; then
	openssl genrsa -out private_key.pem 1024
fi

if [ ! -f public_key.pem ]; then
	openssl rsa -in private_key.pem -out public_key.pem -outform PEM -pubout
fi

echo $1 > name
echo $2 > server

update-rc.d clustermonitor defaults > /dev/null
update-rc.d clustermonitor enable > /dev/null

cat /etc/clustermonitor/public_key.pem

reboot &
